<<<<<<< HEAD
[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

=======
[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

>>>>>>> e5fdfd5d785354d860659661967ec15d88159a54
  